## Basic Configuration
baseurl = "https://tioxy.com/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Gabriel Tiossi"
title = "TIOXY"

theme = "hugo-goa"


## Hugo Built-in Features
disqusShortname = "tioxy"
googleAnalytics = "UA-135523633-1"
enableRobotsTXT = true


## Site Settings
[params]
author = "Gabriel Tiossi"
intro = "Learner and Problem Solver"
description = "One day I'll add a nice description here."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"


## Site Meta Settings
[params.meta]
description = "Just my site."
keywords = "tioxy,blog"


## Social Accounts
[params.social]
github = "tioxy"
instagram = "tioxyofficial"
linkedin = "tioxy"
twitter = "tioxyofficial"
stackoverflow = "7375463/tioxy"
gitlab = "tioxy"
bitbucket = "tioxy"
kickstarter = "tioxy"
steam = "tioxy"
reddit = "tioxy"
twitch = "tioxy"
soundcloud = "tioxy"
telegram = "tioxy"


## Extras
[params.extra]
copyright = "© 2019. Gabriel Tiossi. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true


## Main Menu   
[[menu.main]]
    name = "about"
    identifier = "about"
    url = "/about/"
    weight = 1000
