version: 2.1

executors:
  hugo:
    docker:
      - image: hubci/hugo:0.96.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/hugo
  awscli:
    docker:
      - image: bitnami/aws-cli:1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: /tmp

jobs:
  build:
    executor: hugo
    steps:
      - checkout
      - run: 
          name: Updating submodules
          command: |
            git submodule sync && git submodule update --init
      - run:
          name: Build static files 
          command: |
            HUGO_ENV=production hugo -v -d /tmp/public
      - run:
          name: Test generated HTML files
          command: |
            htmlproofer /tmp/public --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: /tmp/
          paths:
            - public

  deploy:
    executor: awscli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy static files to S3
          command: |
            export PATH="/opt/bitnami/python/bin:/opt/bitnami/aws-cli/bin:/opt/bitnami/aws-cli/venv/bin:$PATH"
            aws s3 sync /tmp/workspace/public/ s3://$S3_BUCKET_NAME --delete
      - run:
          name: Invalidate CDN cache
          command: |
            export PATH="/opt/bitnami/python/bin:/opt/bitnami/aws-cli/bin:/opt/bitnami/aws-cli/venv/bin:$PATH"
            aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"

workflows:
  cd:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
